# Generated by Django 4.1.1 on 2022-10-12 12:26

from django.db import migrations, models
import martor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(max_length=150)),
                ('image', models.ImageField(max_length=150, upload_to='')),
                ('promo', models.BooleanField(default=False)),
                ('promo_image', models.ImageField(max_length=150, upload_to='')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('published', models.BooleanField(default=False)),
                ('markdown_body', martor.models.MartorField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
