# Generated by Django 4.1.1 on 2022-10-12 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_article_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='promo_image',
            field=models.ImageField(max_length=150, null=True, upload_to=''),
        ),
    ]
